#!/usr/bin/env python3
"""
Post-commit hook: print commit info locally.
"""

import sys
import os

_script_dir = os.path.dirname(os.path.abspath(__file__))
if _script_dir not in sys.path:
    sys.path.insert(0, _script_dir)

from git_helpers import get_git_diff, get_repo_info


def main():
    commit_hash, diff = get_git_diff()
    if not commit_hash:
        return

    repo_name, current_branch, remote_name = get_repo_info()
    print(f"[POST-COMMIT] Repo: {repo_name}, Branch: {current_branch}, Remote: {remote_name}, Commit: {commit_hash[:8]}")


if __name__ == '__main__':
    main()
